name: Daily API Call

on:
  schedule:
    - cron: '0 17 * * *'  # Runs every day at 17:00 UTC (18:00 CET/CEST)

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Make API Call
        run: |
          curl -X GET "${{ secrets.API_ENDPOINT }}?ean=${{ secrets.EAN }}" \
          -H "x-api-token: ${{ secrets.API_TOKEN }}" \
          -H "cookie: ${{ secrets.COOKIE }}"
